// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfjdsytcK-ci_Vy5eTOIXvn7jLCddtf9w',
    appId: '1:178321293975:web:7e97871ebe9ba3ab151fd2',
    messagingSenderId: '178321293975',
    projectId: 'recipes-app-5e014',
    authDomain: 'recipes-app-5e014.firebaseapp.com',
    storageBucket: 'recipes-app-5e014.firebasestorage.app',
    measurementId: 'G-4LYLYLFTK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg1HmdBQV-S4O8KLNU5PfQhHXuFI6zKv8',
    appId: '1:178321293975:android:25a25aecfd47376d151fd2',
    messagingSenderId: '178321293975',
    projectId: 'recipes-app-5e014',
    storageBucket: 'recipes-app-5e014.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY1LjVbYyEbvHWZZ3hQMB66hhEtxro3qk',
    appId: '1:178321293975:ios:6d1686ae6f2d9797151fd2',
    messagingSenderId: '178321293975',
    projectId: 'recipes-app-5e014',
    storageBucket: 'recipes-app-5e014.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY1LjVbYyEbvHWZZ3hQMB66hhEtxro3qk',
    appId: '1:178321293975:ios:6d1686ae6f2d9797151fd2',
    messagingSenderId: '178321293975',
    projectId: 'recipes-app-5e014',
    storageBucket: 'recipes-app-5e014.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfjdsytcK-ci_Vy5eTOIXvn7jLCddtf9w',
    appId: '1:178321293975:web:9cd9aa167880b1c3151fd2',
    messagingSenderId: '178321293975',
    projectId: 'recipes-app-5e014',
    authDomain: 'recipes-app-5e014.firebaseapp.com',
    storageBucket: 'recipes-app-5e014.firebasestorage.app',
    measurementId: 'G-43DYG2L4DB',
  );
}
